### PR TITLE
Queue expansion

### PR DESCRIPTION
**Pull request by benwingerter**

### CODE REVIEW

**Comment by benwingerter** [comment]
Mark as incomplete or cancel on the queue appointment page doesn't seem to work even if it's on the last step

**Comment by benwingerter** [comment]
Everything else works great

**Comment by benwingerter** [comment]
> Mark as incomplete or cancel on the queue appointment page doesn't seem to work even if it's on the last step

Actually, mark cancel works. I think it's an ng-disabled logic bug. But this button's effect doesn't occur until page reload

**Review by jcarrigan2 — COMMENTED** [review]
Need to improve cancel/incomplete functionality at some point

**Review by jcarrigan2 — APPROVED** [review]

**Pull request merged**
